<#
.SYNOPSIS
    Scaffolds a new EF6 migration for the Cis.Data project.

.DESCRIPTION
    Equivalent of "dotnet ef migrations add <Name>" for .NET Framework 4.7 + EF6.
    Builds Cis.Data, extracts the current model snapshot, then creates:
      - Cis.Data/Migrations/<Timestamp>_<Name>.cs       (empty Up/Down scaffold)
      - Cis.Data/Migrations/<Timestamp>_<Name>.Designer.cs  (with snapshot embedded)

.EXAMPLE
    .\Add-Migration.ps1 -Name AddProductExpiredFlag
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$Name
)

$ErrorActionPreference = "Stop"
$root      = $PSScriptRoot
$migrDir   = Join-Path $root "Cis.Data\Migrations"
$buildOut  = Join-Path $root "TempBuild"
$snapFile  = Join-Path $buildOut "model_snapshot.txt"
$configSrc = Join-Path $root "Cis.Data\bin\Release\net47\Cis.Data.dll.config"
$snapCs    = Join-Path $root "GetModelSnapshot.cs"
$snapExe   = Join-Path $buildOut "GetModelSnapshot.exe"
$csc       = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"

# ── 1. Build Cis.Data ────────────────────────────────────────────────────────
Write-Host ""
Write-Host "[1/4] Building Cis.Data..." -ForegroundColor Cyan
dotnet build "$root\Cis.Data\Cis.Data.csproj" -c Release -o $buildOut --nologo -v quiet
if ($LASTEXITCODE -ne 0) { Write-Error "Build failed."; exit 1 }

# ── 2. Compile GetModelSnapshot into TempBuild (uses fresh DLLs) ─────────────
Write-Host "[2/4] Extracting model snapshot..." -ForegroundColor Cyan
$refArgs = (Get-ChildItem "$buildOut\*.dll" | ForEach-Object { "/r:$($_.FullName)" })
& $csc /out:$snapExe /nologo @refArgs $snapCs
if ($LASTEXITCODE -ne 0) { Write-Error "GetModelSnapshot compile failed."; exit 1 }

# Copy config so EF6 can resolve connection string
Copy-Item $configSrc ($snapExe + ".config") -Force

# Run from TempBuild so it loads the fresh DLLs in that directory
Push-Location $buildOut
& $snapExe
Pop-Location
if ($LASTEXITCODE -ne 0) { Write-Error "GetModelSnapshot.exe failed."; exit 1 }

# Also update root model_snapshot.txt for reference
Copy-Item $snapFile (Join-Path $root "model_snapshot.txt") -Force

$snapshot = (Get-Content $snapFile -Raw).Trim()
Write-Host "      Snapshot: $($snapshot.Length) chars" -ForegroundColor DarkGray

# Cleanup snapshot exe
Remove-Item $snapExe -Force -ErrorAction SilentlyContinue
Remove-Item ($snapExe + ".config") -Force -ErrorAction SilentlyContinue
Remove-Item ($snapExe + ".pdb") -Force -ErrorAction SilentlyContinue

# ── 3. Generate migration ID (timestamp) ─────────────────────────────────────
$timestamp = (Get-Date).ToString("yyyyMMddHHmmssf")
$migId     = "${timestamp}_${Name}"
$className = $Name

Write-Host "[3/4] Creating migration files for '$migId'..." -ForegroundColor Cyan

# ── 4a. Migration .cs file ────────────────────────────────────────────────────
$migCs = @"
namespace Cis.Data.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class $className : DbMigration
    {
        public override void Up()
        {
            // TODO: add schema changes here
            // e.g. AddColumn("dbo.Product", "IsActive", c => c.Boolean(nullable: false, defaultValue: true));
        }

        public override void Down()
        {
            // TODO: reverse the changes above
        }
    }
}
"@

$csPath = Join-Path $migrDir "${migId}.cs"
[System.IO.File]::WriteAllText($csPath, $migCs, [System.Text.Encoding]::UTF8)
Write-Host "      Created: Cis.Data\Migrations\${migId}.cs" -ForegroundColor Green

# ── 4b. Designer .cs file ─────────────────────────────────────────────────────
$designerCs = @"
// <auto-generated />
namespace Cis.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class $className : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "$migId"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return "$snapshot"; }
        }
    }
}
"@

$designerPath = Join-Path $migrDir "${migId}.Designer.cs"
[System.IO.File]::WriteAllText($designerPath, $designerCs, [System.Text.Encoding]::UTF8)
Write-Host "      Created: Cis.Data\Migrations\${migId}.Designer.cs" -ForegroundColor Green

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "[4/4] Done. Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit Up() and Down() in:" -ForegroundColor White
Write-Host "       Cis.Data\Migrations\${migId}.cs" -ForegroundColor Yellow
Write-Host "  2. Run the migration:" -ForegroundColor White
Write-Host "       .\Update-Database.ps1" -ForegroundColor Yellow
